### PR TITLE
Add kornia

### PR DESCRIPTION
**Pull request by Hennzau**
Oups, I did something wrong while merging another PR, i can not open this PR again. See #8

### CODE REVIEW

**Comment by haixuanTao** [comment]
Wow! So fast!

Fyi they have a read webcam example that could be useful: https://github.com/kornia/kornia-rs/tree/main/examples/webcam

**Comment by Hennzau** [comment]
> Wow! So fast!
> 
> Fyi they have a read webcam example that could be useful: https://github.com/kornia/kornia-rs/tree/main/examples/webcam

Thanks! I find Kornia really good looking, I just have 1-2 other things to do before (i'm struggling consuming pyarrow objects)

**Comment by edgarriba** [comment]
@Hennzau the latest published is 0.1.5 -- however, there's a massive refactor (as a highlight removing ndarray to leverage arrow::Buffer for tensor/image). The code is under the [0.1.6-rc2](https://github.com/kornia/kornia-rs/tree/v0.1.6-rc2) tag to be stable and released by the end of the month. You can give it a try or just use the latest 0.1.5 and i can update myself later.

**Comment by Hennzau** [comment]
> @Hennzau the latest published is 0.1.5 -- however, there's a massive refactor (as a highlight removing ndarray to leverage arrow::Buffer for tensor/image). The code is under the [0.1.6-rc2](https://github.com/kornia/kornia-rs/tree/v0.1.6-rc2) tag to be stable and released by the end of the month. You can give it a try or just use the latest 0.1.5 and i can update myself later.

all right! I think i'll go for the release candidate! Maybe I'll ask questions on discord in the coming days :)

**Pull request merged**
